services:
  nginx_1:
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile
    depends_on:
      - node_1
    networks:
      - default
    expose:
      - "80"

  node_1:
    build:
      context: ./docker
      dockerfile: node/Dockerfile
    command: sh -c 'npm install && npm start'
    networks:
      - default
    volumes:
      - ./app:/app

networks:
  default:
    external: false
