services:
  nginx_2:
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile
    depends_on:
      - node_2
    networks:
      - default
    expose:
      - "80"

  node_2:
    build:
      context: ./docker
      dockerfile: node/Dockerfile
    command: sh -c 'npm install && npm start'
    networks:
      - default
    volumes:
      - ./app:/app

networks:
  default:
    external: false
